### ISSUE TITLE
chrome and safari updated with breaking "webkitHidden" property change?

### ISSUE THREAD

**Issue by erikyuzwa** [vissense/vissense#35] opened 2016-04-27 20:31 UTC
This library works fine that I can see on the latest Firefox.
When I tried to use it in either Chrome or MacOS Safari, I'm seeing:

_Cannot read property 'webkitHidden' of undefined_

The Safari console debugger provides a slightly better trace:
<img width="533" alt="screen shot 2016-04-27 at 2 30 27 pm" src="https://cloud.githubusercontent.com/assets/962434/14867212/b62c4c26-0c84-11e6-8db9-3e1ffedb079e.png">

**Comment by erikyuzwa** [comment] 2016-04-27 20:54
Sorry. Turns out `document` was `undefined` which eventually led me back to webpack. 
For future reference, you need to expose it via a script loader
`{ test: /vissense/, loader: 'exports?VisSense!script'},`

**Comment by theborakompanioni** [comment] 2016-04-28 10:51
@erikyuzwa Nonetheless - thank you for reporting.

**Comment by Zhouzi** [comment] 2016-05-10 10:03
I just faced the same issue so thanks @erikyuzwa. To solve it, I had to:

1. `npm install script-loader --save-dev` - makes VisSense run in the global context
2. `npm install exports-loader --save-dev` - to properly export VisSense as a module and make it work with ES2015 modules
3. Add `{ test: /vissense/, loader: 'exports?VisSense!script'}` to the list of `module.loaders`

The issue could be caused by an access to the global `document` object instead of `window.document` but I didn't find such code anywhere. Any idea of what's happening @erikyuzwa?

**Comment by erikyuzwa** [comment] 2016-05-11 05:55
I think it's here @Zhouzi 
https://github.com/vissense/vissense/blob/master/dist/vissense.js#L209

**Comment by Zhouzi** [comment] 2016-05-11 10:58
Actually in this case, `document` is passed as an argument at [#L824](https://github.com/vissense/vissense/blob/master/lib/vissense.js#L824) which points to `window.document` [#L860](https://github.com/vissense/vissense/blob/master/lib/vissense.js#L860). I'll eventually spend some more time troubleshooting this but I don't really see what's happening at the moment.

**Comment by theborakompanioni** [comment] 2016-05-24 07:28
@Zhouzi & @erikyuzwa Please report any findings or provide details to reproduce the problem. I am glad if I can help. I am currently in the process of rewriting VisSense in ES6 (as backward compatible as possible) - maybe that solves your issues.

**Comment by bmwertman** [comment] 2017-04-21 17:04
I'm trying to use this with my Vue.js application. Without the fix mentioned by either @Zhouzi or @erikyuzwa I get a similar error;
```
Uncaught TypeError: Cannot read property 'webkitHidden' of undefined
    at eval (eval at <anonymous> (app.js:1125), <anonymous>:210:32)
    at forEach (eval at <anonymous> (app.js:1125), <anonymous>:68:35)
    at eval (eval at <anonymous> (app.js:1125), <anonymous>:209:194)
    at createVisibilityApi (eval at <anonymous> (app.js:1125), <anonymous>:229:10)
    at eval (eval at <anonymous> (app.js:1125), <anonymous>:453:24)
    at withWindow (eval at <anonymous> (app.js:1125), <anonymous>:5:23)
    at VueComponent.visibility (eval at <anonymous> (app.js:1033), <anonymous>:63:70)
    at VueComponent.boundFn [as visibility] (eval at <anonymous> (app.js:723), <anonymous>:126:14)
    at VueComponent.mounted (eval at <anonymous> (app.js:1033), <anonymous>:26:10)
    at callHook (eval at <anonymous> (app.js:723), <anonymous>:2754:19)
```
With their fix I get an error that looks like I never installed `vissense` even though it's in `node_modules`
```
This dependency was not found in node_modules:

* vissense 
```

**Comment by tommhuth** [comment] 2017-05-09 11:07
this should be fixed, any news on progress?

**Comment by theborakompanioni** [comment] 2017-05-09 18:52
No progress yet. Problem is known and identified. But I do not know how to fix it properly. Can you provide a showcase?

**Comment by theborakompanioni** [comment] 2017-05-16 19:11
@tommhuth Would it be possible for you to share some details on your build process/how you are including the library?

**Comment by diachedelic** [comment] 2017-10-18 02:28
The issue can be found in `./templates/umd-vissense-no-conflict.hbs`, where the `module.exports` value is a factory function requiring `window`, not the `VisSense` constructor.

My solution:

```
import VisSenseFactory from 'vissense'

// requires window when initialised from CommonJS with WebPack,
// see https://github.com/vissense/vissense/issues/35
const VisSense = VisSenseFactory(window)

VisSense(el).monitor({ ... }).start()
```

**Comment by theborakompanioni** [comment] 2017-10-26 16:23
@diachedelic thanks for sharing. I am not aware of a proper solution to the problem yet.

**Closed** 2019-02-07 13:40 UTC
