### ISSUE TITLE
How can I stop monitor after first element visibility?

### ISSUE THREAD

**Issue by codev0** [vissense/vissense#32] opened 2016-02-03 15:26 UTC
In my case I have piechart plugin. And show it when visible. Its works.
But plugin initialized each time seen.
```
if($("div").is(".statistic-block")) {
    var $statsBlock = $(".statistic-block");

    var $statsBlockVisibility = VisSense($statsBlock[0]).monitor({
      visible: function() {
        $('#myStat1').circliful();
        $('#myStat').circliful();
        $('#myStat3').circliful();
        $('#myStat2').circliful();

        $statsBlock.addClass("visible");
      }
    }).start();

    if($statsBlock.hasClass("visible")) {
      console.log("stop");
      $statsBlockVisibility.stop();
    }
  }
```

**Comment by theborakompanioni** [comment] 2016-02-03 19:11
@codev0 You can stop the monitor as soon as the element is visible. All hooks receive the monitor object as first argument, so you can stop it like this:
```
VisSense($statsBlock[0]).monitor({
  visible: function(monitor) {
    $('#myStat1').circliful();
    $('#myStat').circliful();
    $('#myStat3').circliful();
    $('#myStat2').circliful();

    monitor.stop();
  }
}).start();
```

**Comment by codev0** [comment] 2016-02-07 19:38
@theborakompanioni Hi. Thanks.
Its work.
But if the video block is visible right after the page is loaded, then it is executed again every time the block enters viewport

**Comment by theborakompanioni** [comment] 2016-02-08 08:11
@codev0 Can you provide some code so I can reproduce the problem?

**Comment by theborakompanioni** [comment] 2016-02-09 10:13
@codev0 I played around with the [video demo](https://jsbin.com/maqaco/edit?js,output) but could not reproduce your problem. Can you provide further information?

**Comment by codev0** [comment] 2016-02-09 10:15
@theborakompanioni 
https://output.jsbin.com/hixijujecu

**Comment by theborakompanioni** [comment] 2016-02-09 11:23
@codev0 Ah, ok. I could reproduce the problem - thanks for reporting. I'll take a look at it this week and keep you updated. Thanks!

**Comment by theborakompanioni** [comment] 2016-02-09 20:39
@codev0 Thanks for your effort. Has been fixed with ca93cab9. [v0.10.0](https://github.com/vissense/vissense/releases/tag/0.10.0) has been released. This behavior should have been covered by tests long ago!

**Closed** 2016-02-10 10:01 UTC
Labels: bug, fix asap
